version: '3'

volumes:
  pg_wish_list_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_wish_list_data:/var/lib/postgresql/data
  bot-backend: 
    build: ./bot_v2 
    depends_on: 
      - db 
    env_file: .env
  api-backend: 
    build: ./wish_list 
    depends_on: 
      - db 
    env_file: .env
    volumes: 
      - static:/backend_static
    ports: 
      - 80:80 
  nginx: 
      build: ./nginx 
      depends_on:
        - api-backend 
      env_file: .env 
      volumes:
        - static:/staticfiles
      ports: 
        - 8000:80 